title: Terraform - Rstudio Server Digital Ocean
description: Terraform - Rstudio Server Digital Ocean
theme: just-the-docs


url: https://gonzalezben81.github.io/terraform-digitalocean-rstudio-server/

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

aux_links:
  Rstudio Server Digital Ocean Repo: https://github.com/gonzalezben81/terraform-digitalocean-rstudio-server.git
  Digital Ocean Images: https://docs.digitalocean.com/products/droplets/details/images/
  Digital Ocean Droplet Options: https://slugs.do-api.dev/
  Droplet Info: https://docs.digitalocean.com/reference/terraform/reference/data-sources/droplet/
  
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true  

# For copy button on code
enable_copy_code_button: true

# By default, consuming the theme as a gem leaves mermaid disabled; it is opt-in
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

  # Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"



# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: light

# Show navigation error report
nav_error_report: true # default is false/nil.


liquid:
  error_mode: strict
  strict_filters: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
  
# Footer content
# appears at the bottom of every page's main content
footer_content: 'Copyright &copy; 2025-26 Ben Gonzalez. Distributed by an <a href="https://github.com/gonzalezben81/aws-cloud-templates/tree/main/LICENSE.txt">MIT license.</a> <a href="https://www.netlify.com/">This site is powered by Netlify.</a>'

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jemoji
  - jekyll-default-layout  

kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false
      
# ga-tracking: G-N1JV4PDVW6
# ga_tracking_anonymize_ip: true

# Google Analytics
google_analytics:
  enabled: true
  id: G-N1JV4PDVW6  # Replace with your Measurement ID